name: hmssdk_flutter_example
description: Demonstrates how to use the hmssdk_flutter plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.11.0
environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hms_room_kit:
    path: ../../hms_room_kit

  lottie: ^3.3.2
  firebase_crashlytics: ^5.0.3
  firebase_core: ^4.2.0
  firebase_performance: ^0.11.1+1
  package_info_plus: ^9.0.0
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  mobile_scanner: ^7.1.3
  app_links: ^6.4.1
  uuid: ^4.5.1
  flutter_foreground_task:
    git:
      url: https://github.com/100mslive/flutter-foreground-task-v2.git
      ref: gradle-8-error-fix

  flutter_svg: ^2.2.1
  provider: ^6.1.5+1
dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/
    - packages/hmssdk_flutter/assets/sdk-versions.json
