name: hmssdk_flutter
description: Add Real Time Audio & Video calls, Interactive Live Streaming & Recording, Chat, HLS, RTMP,  PiP, CallKit, VoIP, Video conferencing, Stream Player & WebRTC-based communications API
version: 1.11.0
homepage: https://www.100ms.live/
repository: https://github.com/100mslive/100ms-flutter
issue_tracker: https://github.com/100mslive/100ms-flutter/issues
documentation: https://www.100ms.live/docs

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: live.hms.hmssdk_flutter
        pluginClass: HmssdkFlutterPlugin
      ios:
        pluginClass: HmssdkFlutterPlugin

  assets:
    - lib/assets/sdk-versions.json
